services:
  - type: web
    name: nexotv-backend
    env: node
    plan: free
    region: ohio
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run prisma:generate && cd backend && npx nest build
    startCommand: node backend/dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres.wvwdbxhglknvgbwnihhs:Ines%2A2026%2AEnrique@aws-0-us-east-2.pooler.supabase.com:6543/postgres?pgbouncer=true&schema=public
      - key: DIRECT_URL
        value: postgresql://postgres.wvwdbxhglknvgbwnihhs:Ines%2A2026%2AEnrique@aws-0-us-east-2.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET
        value: nexotv_super_secret_jwt_key_2026_change_in_production
      - key: JWT_EXPIRES_IN
        value: 7d
