export interface Channel {
  id: string;
  name: string;
  category: 'ARGENTINA' | 'DEPORTES' | 'CINE' | 'NOTICIAS' | 'INFANTIL' | 'DOCUMENTALES' | 'MUSICA';
  number: number;
  logoUrl?: string;
  logoEmoji: string;
  nowPlaying: string;
  streamUrl: string;
  isHD: boolean;
}

export interface Movie {
  id: string;
  title: string;
  category: 'ESTRENOS' | 'ACCION' | 'COMEDIA' | 'TERROR' | 'SCIFI' | 'INFANTIL' | 'DRAMA';
  year: number;
  duration: string;
  rating: string;
  synopsis: string;
  posterEmoji: string;
  posterUrl?: string;
  streamUrl: string;
}

export interface SeriesEpisode {
  id: string;
  episodeNumber: number;
  title: string;
  duration: string;
  synopsis: string;
  streamUrl: string;
}

export interface Series {
  id: string;
  title: string;
  category: 'DRAMA' | 'ACCION' | 'COMEDIA' | 'SCIFI' | 'ANIME';
  seasonsCount: number;
  episodesCount: number;
  rating: string;
  synopsis: string;
  posterEmoji: string;
  episodes: SeriesEpisode[];
}

export const CHANNELS_CATALOG: Channel[] = [
  {
    "id": "ar-1",
    "name": "5TV Corrientes (480p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 1,
    "logoUrl": "https://i.imgur.com/mSn7ACs.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://www.coninfo.net:1935/tvcinco/live1/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-2",
    "name": "24/7 Canal de Noticias",
    "category": "NOTICIAS",
    "number": 2,
    "logoUrl": "https://i.imgur.com/4hDCB1M.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://panel.host-live.com:19360/cn247tv/cn247tv.m3u8",
    "isHD": false
  },
  {
    "id": "ar-3",
    "name": "ABTV Bariloche",
    "category": "ARGENTINA",
    "number": 3,
    "logoUrl": "https://i.imgur.com/l4TSfDr.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videostream.shockmedia.com.ar/hls/abtvbariloche/abtvbariloche.m3u8",
    "isHD": false
  },
  {
    "id": "ar-4",
    "name": "Aire de Santa Fe (1080p)",
    "category": "ARGENTINA",
    "number": 4,
    "logoUrl": "https://i.imgur.com/60vSWW0.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://unlimited1-us.dps.live/airedesantafetv/airedesantafetv.smil/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-5",
    "name": "Alterna TV (720p) [Not 24/7]",
    "category": "CINE",
    "number": 5,
    "logoUrl": "https://tv.alterna.ar/alternatv.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://tv.alterna.ar/stream/hls/live.m3u8",
    "isHD": true
  },
  {
    "id": "ar-6",
    "name": "AMC Latin America (1080p)",
    "category": "CINE",
    "number": 6,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/AMC_logo_2019.svg/960px-AMC_logo_2019.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://15.204.246.24:8080/AMCHD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-7",
    "name": "America TV (1080p)",
    "category": "ARGENTINA",
    "number": 7,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Am%C3%A9rica_TV_%28Nuevo_logo_Junio_2020%29.png/500px-Am%C3%A9rica_TV_%28Nuevo_logo_Junio_2020%29.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://playcom.trapemn.tv:1935/transcoderip/america.stream/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-8",
    "name": "Argentinísima Satelital (540p)",
    "category": "ARGENTINA",
    "number": 8,
    "logoUrl": "https://i.imgur.com/xFgJawa.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream1.sersat.com/hls/argentinisima.m3u8",
    "isHD": false
  },
  {
    "id": "ar-9",
    "name": "AXN Latin America South",
    "category": "CINE",
    "number": 9,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/AXN_logo_%282015%29.svg/960px-AXN_logo_%282015%29.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://45.228.235.116:8000/play/a0iy/index.m3u8",
    "isHD": false
  },
  {
    "id": "ar-10",
    "name": "Azahares Radio Multimedia (720p)",
    "category": "MUSICA",
    "number": 10,
    "logoUrl": "https://i.imgur.com/g1BFoSs.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streamyes.alsolnet.com/azaharesfm/live/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-11",
    "name": "Bayres TV (720p)",
    "category": "ARGENTINA",
    "number": 11,
    "logoUrl": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjKrroOZ4RYMYlzGqMQjiIO2QbRNVndEM9PiC-CaRn0PO2AoB_YKyrt6Eigzh4M1gPZaVn5udDL5YzrzxAmyQCj_HTF8Pszo46dk9dABt9TpepY43_IEzT80atZEMaiMcdrqt3lmxAbZYaLwCgr6vDUgV1HlvmhIOJ99UlwAhG2FoHgtCm13CWEugV7Bvg/w1200-h630-p-k-no-nu/bayres-tv-removebg-preview.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streaming01.mikrolive.tv/bayrestv/live/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-12",
    "name": "Beats Radio (480p)",
    "category": "MUSICA",
    "number": 12,
    "logoUrl": "https://i.imgur.com/zkNUO5p.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videostream.shockmedia.com.ar:19360/beatsradio/beatsradio.m3u8",
    "isHD": false
  },
  {
    "id": "ar-13",
    "name": "Bragado TV",
    "category": "ARGENTINA",
    "number": 13,
    "logoUrl": "https://i.imgur.com/xP88fKG.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://mp.panelchs.com:1936/8028/ngrp:8028_all/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-14",
    "name": "Bravo TV (1080p)",
    "category": "ARGENTINA",
    "number": 14,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Bravotv.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://redirector.rudo.video/hls-video/c54ac2799874375c81c1672abb700870537c5223/bravo/bravo.smil/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-15",
    "name": "BVC",
    "category": "ARGENTINA",
    "number": 15,
    "logoUrl": "https://i.imgur.com/I06TSx0.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vivo.solumedia.com:19360/bvnet/bvnet.m3u8",
    "isHD": false
  },
  {
    "id": "ar-16",
    "name": "Cable Imagen Armstrong (540p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 16,
    "logoUrl": "https://i.imgur.com/U9NuJQC.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.com.ar/casse/casse/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-17",
    "name": "Cadena 103 (720p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 17,
    "logoUrl": "https://i.imgur.com/vBsry35.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://arcast.net:1935/cadena103/cadena103/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-18",
    "name": "Canal 2 de Ushuaia (1080p)",
    "category": "ARGENTINA",
    "number": 18,
    "logoUrl": "https://i.ibb.co/q5NPdK2/canal2-logo.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://nd106.republicaservers.com:4433/hls/c6611/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-19",
    "name": "Canal 2 Gualeguay",
    "category": "ARGENTINA",
    "number": 19,
    "logoUrl": "https://i.imgur.com/TOlncyp.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.net:4443/gualeguay/gualeguay/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-20",
    "name": "Canal 2 Misiones (1080p)",
    "category": "ARGENTINA",
    "number": 20,
    "logoUrl": "https://i.imgur.com/YqTNXDf.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://nd106.republicaservers.com:4433/hls/canal2misioness/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-21",
    "name": "Canal 2 NexTV Rafaela (720p)",
    "category": "ARGENTINA",
    "number": 21,
    "logoUrl": "https://i.imgur.com/hgj3CaR.jpeg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://edge.enhdtv.com/nexthd/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-22",
    "name": "Canal 3 Formosa",
    "category": "ARGENTINA",
    "number": 22,
    "logoUrl": "https://i.imgur.com/rVDrNIy.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stmvideo6.livecastv.com/agenfor/agenfor/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-23",
    "name": "Canal 3 La Pampa (1080p)",
    "category": "ARGENTINA",
    "number": 23,
    "logoUrl": "https://i.imgur.com/SsNFudZ.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.com.ar/c3lapampa/ngrp:c3lapampa_all/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-24",
    "name": "Canal 3 Las Heras (720p)",
    "category": "ARGENTINA",
    "number": 24,
    "logoUrl": "https://i.imgur.com/bd2afET.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.com.ar/canal3/canal3/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-25",
    "name": "Canal 3 Pinamar",
    "category": "ARGENTINA",
    "number": 25,
    "logoUrl": "https://i.imgur.com/IABFaH1.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://intelincloud01.com.ar/hls/cn3/index.m3u8",
    "isHD": false
  },
  {
    "id": "ar-26",
    "name": "Canal 3 Tacural",
    "category": "ARGENTINA",
    "number": 26,
    "logoUrl": "https://i.imgur.com/RKvSa52.jpeg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://vivo.canal3tacural.com.ar:8081/hls/stream.m3u8",
    "isHD": false
  },
  {
    "id": "ar-27",
    "name": "Canal 4 Esquel",
    "category": "ARGENTINA",
    "number": 27,
    "logoUrl": "https://i.imgur.com/6kbOr16.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.com.ar/canal4esquel/canal4esquel/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-28",
    "name": "Canal 4 Jujuy",
    "category": "ARGENTINA",
    "number": 28,
    "logoUrl": "https://i.imgur.com/qB6I274.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://5cd577a3dd8ec.streamlock.net/CANAL4/smil:CANAL4.smil/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-29",
    "name": "Canal 4 Posadas (576p)",
    "category": "ARGENTINA",
    "number": 29,
    "logoUrl": "https://i.imgur.com/tElJr3e.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://iptv.ixfo.com.ar:30443/live/C4POS/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-30",
    "name": "Canal 4 San Juan (576p)",
    "category": "ARGENTINA",
    "number": 30,
    "logoUrl": "https://i.imgur.com/MsCnwRA.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streamlov.alsolnet.com/canal4sanjuan/live/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-31",
    "name": "Canal 4 Teleaire",
    "category": "ARGENTINA",
    "number": 31,
    "logoUrl": "https://i.imgur.com/XyiNvbY.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stmvideo6.livecastv.com/canal4/canal4/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-32",
    "name": "Canal 4 Villa Dolores",
    "category": "ARGENTINA",
    "number": 32,
    "logoUrl": "https://i.imgur.com/ZKSnGfw.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stmvideo3.livecastv.com/canal4vd/canal4vd/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-33",
    "name": "Canal 5 Del Pueblo [Not 24/7]",
    "category": "ARGENTINA",
    "number": 33,
    "logoUrl": "https://i.ibb.co/XzcYYMc/Canal-5-alcorta-ver.jpg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stmv4.voxtvhd.com.br/canal5pueblo/canal5pueblo/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-34",
    "name": "Canal 5 Santa Fe (240p)",
    "category": "ARGENTINA",
    "number": 34,
    "logoUrl": "https://i.imgur.com/WX0esjQ.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.com.ar/c5sf/c5sf/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-35",
    "name": "Canal 5 TV Chepes",
    "category": "ARGENTINA",
    "number": 35,
    "logoUrl": "https://i.imgur.com/AzEqroq.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videostream.shockmedia.com.ar:19360/canal5alfatvchepes/canal5alfatvchepes.m3u8",
    "isHD": false
  },
  {
    "id": "ar-36",
    "name": "Canal 6 Posadas (1080p)",
    "category": "ARGENTINA",
    "number": 36,
    "logoUrl": "https://i.imgur.com/OamBiS5.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://iptv.ixfo.com.ar:30443/live/c6digital/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-37",
    "name": "Canal 6 Viento Recio",
    "category": "ARGENTINA",
    "number": 37,
    "logoUrl": "https://i.imgur.com/liyTNzK.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stmvideo6.livecastv.com/vientorecio/vientorecio/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-38",
    "name": "Canal 7 Jujuy",
    "category": "ARGENTINA",
    "number": 38,
    "logoUrl": "https://i.imgur.com/K0jk8p4.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.live/canal7jujuy/ngrp:canal7jujuy_all/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-39",
    "name": "Canal 7 Neuquén (1080p)",
    "category": "ARGENTINA",
    "number": 39,
    "logoUrl": "https://i.ibb.co/BrvQsWm/C7neuquenlogo2023.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.com.ar/c7nq/ngrp:c7nq_all/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-40",
    "name": "Canal 7 Salta (1080p)",
    "category": "ARGENTINA",
    "number": 40,
    "logoUrl": "https://i.imgur.com/CudG6sl.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vivo.solumedia.com:19360/cooperativa/cooperativa.m3u8",
    "isHD": true
  },
  {
    "id": "ar-41",
    "name": "Canal 7 Santiago del Estero (720p)",
    "category": "ARGENTINA",
    "number": 41,
    "logoUrl": "https://i.imgur.com/iJMH0UK.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.com.ar/envivo/castv/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-42",
    "name": "Canal 8 San Juan (720p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 42,
    "logoUrl": "https://files.catbox.moe/f7jbdo.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://live20.bozztv.com/akamaissh101/ssh101/canal8sanjuan/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-43",
    "name": "Canal 9 Link",
    "category": "ARGENTINA",
    "number": 43,
    "logoUrl": "https://audios.radiosnet.com.ar/imgwikidat/img_cuerpo/canal+9+buenos+aires9.jpg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://617c5175c970b.streamlock.net:4444/9linklivert/smil:9linkmultibr.smil/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-44",
    "name": "Canal 9 Litoral (720p)",
    "category": "ARGENTINA",
    "number": 44,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Canal_9_Litoral_2021.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.live/ahora/ahora/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-45",
    "name": "Canal 9 Resistencia (720p)",
    "category": "ARGENTINA",
    "number": 45,
    "logoUrl": "https://i.imgur.com/xqgRFpC.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://coninfo.net:1935/9linklivert/smil:9linkmultibr.smil/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-46",
    "name": "Canal 10 Cordoba",
    "category": "ARGENTINA",
    "number": 46,
    "logoUrl": "https://i.imgur.com/87WCHtd.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.net:4443/canal10/ngrp:canal10_all/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-47",
    "name": "Canal 10 Mar del Plata",
    "category": "ARGENTINA",
    "number": 47,
    "logoUrl": "https://i.imgur.com/bq29sfG.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://g1.mc-hor.transport.edge-access.net/a12/ngrp:canal10mdq-100044_all/Playlist.m3u8?sense=true",
    "isHD": false
  },
  {
    "id": "ar-48",
    "name": "Canal 12 Puerto Madryn (720p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 48,
    "logoUrl": "https://i.imgur.com/VYcTRbd.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://5f700d5b2c46f.streamlock.net/madryntv/madryntv/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-49",
    "name": "Canal 13 Jujuy TV (720p)",
    "category": "ARGENTINA",
    "number": 49,
    "logoUrl": "https://i.imgur.com/lmKLiJ3.jpg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://genexservicios.com:19360/canal13jujuy/canal13jujuy.m3u8",
    "isHD": true
  },
  {
    "id": "ar-50",
    "name": "Canal 13 La Rioja (480p)",
    "category": "ARGENTINA",
    "number": 50,
    "logoUrl": "https://i.imgur.com/OI97Sgq.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://arcast.net:1935/mp/mp/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-51",
    "name": "Canal 13 San Luis",
    "category": "ARGENTINA",
    "number": 51,
    "logoUrl": "https://i.imgur.com/NcfMC29.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.radiosmundiales.com:19360/sanluismas/sanluismas.m3u8",
    "isHD": false
  },
  {
    "id": "ar-52",
    "name": "Canal 21 TV (1080p)",
    "category": "ARGENTINA",
    "number": 52,
    "logoUrl": "https://i.imgur.com/Am7yMXg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://iptv.ixfo.com.ar:30443/c21tv/hd/c21tv/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-53",
    "name": "Canal 22 (720p)",
    "category": "ARGENTINA",
    "number": 53,
    "logoUrl": "https://i.imgur.com/R4wXVxf.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://5f700d5b2c46f.streamlock.net/canal22/canal22/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-54",
    "name": "Canal 26 (1080p)",
    "category": "NOTICIAS",
    "number": 54,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Canal_26_logo_%282022%29.svg/500px-Canal_26_logo_%282022%29.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream-gtlc.telecentro.net.ar/hls/canal26hls/main.m3u8",
    "isHD": true
  },
  {
    "id": "ar-55",
    "name": "Canal 50 Morteros",
    "category": "ARGENTINA",
    "number": 55,
    "logoUrl": "https://i.imgur.com/IDhgBav.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://online.coopmorteros.coop/canal50/vivo.m3u8",
    "isHD": false
  },
  {
    "id": "ar-56",
    "name": "Canal 79 La Costa (240p)",
    "category": "ARGENTINA",
    "number": 56,
    "logoUrl": "https://i.imgur.com/HYuSqJy.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streamconex.com:19360/lacosta/lacosta.m3u8",
    "isHD": false
  },
  {
    "id": "ar-57",
    "name": "Canal 79 Mar del Plata",
    "category": "ARGENTINA",
    "number": 57,
    "logoUrl": "https://i.imgur.com/I93ypGY.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streamconex.com:19360/mardelplata/mardelplata.m3u8",
    "isHD": false
  },
  {
    "id": "ar-58",
    "name": "Canal 79 Puan (240p)",
    "category": "ARGENTINA",
    "number": 58,
    "logoUrl": "https://i.imgur.com/HYuSqJy.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streamconex.com:19360/puan/puan.m3u8",
    "isHD": false
  },
  {
    "id": "ar-59",
    "name": "Canal 79 Santa Clara del Mar (240p)",
    "category": "ARGENTINA",
    "number": 59,
    "logoUrl": "https://i.imgur.com/I93ypGY.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streamconex.com:19360/santaclara-1/santaclara-1.m3u8",
    "isHD": false
  },
  {
    "id": "ar-60",
    "name": "Canal 79 Villa Maza",
    "category": "ARGENTINA",
    "number": 60,
    "logoUrl": "https://i.imgur.com/HYuSqJy.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streamconex.com:19360/villamaza/villamaza.m3u8",
    "isHD": false
  },
  {
    "id": "ar-61",
    "name": "Canal 99 Miramar",
    "category": "ARGENTINA",
    "number": 61,
    "logoUrl": "https://i.imgur.com/PblsZxz.jpeg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vivo.solumedia.com:19360/cardinal/cardinal.m3u8",
    "isHD": false
  },
  {
    "id": "ar-62",
    "name": "Canal E (720p)",
    "category": "NOTICIAS",
    "number": 62,
    "logoUrl": "https://i.ibb.co/y4pkxH3/Qtc8-M2-PG-400x400.jpg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://unlimited1-us.dps.live/perfiltv/perfiltv.smil/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-63",
    "name": "Canal Luz",
    "category": "ARGENTINA",
    "number": 63,
    "logoUrl": "https://i.imgur.com/GnY6dNT.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://g4.vxral-hor.transport.edge-access.net/a11/ngrp:canal_luz01-100009_all/Playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-64",
    "name": "Canal Orbe 21",
    "category": "ARGENTINA",
    "number": 64,
    "logoUrl": "https://i.imgur.com/USD6Wn8.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.net:4443/canal21/ngrp:canal21_all/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-65",
    "name": "Canal Provincial (360p)",
    "category": "ARGENTINA",
    "number": 65,
    "logoUrl": "https://i.imgur.com/bXHHtcb.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streaming.telered.com.ar/provincial/streaming/mystream.m3u8",
    "isHD": false
  },
  {
    "id": "ar-66",
    "name": "Canal Pulpo TV",
    "category": "ARGENTINA",
    "number": 66,
    "logoUrl": "https://new.opencaster.com/uploads/logos/logo_306_1756336707.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vs20.live.opencaster.com/canalpulpotv_bdeee6e2/index.m3u8",
    "isHD": false
  },
  {
    "id": "ar-67",
    "name": "Canal Santa María (360p)",
    "category": "ARGENTINA",
    "number": 67,
    "logoUrl": "https://www.canalsantamaria.com.ar/images/santamaria_logo.jpg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streaming.telered.com.ar/santa-maria/streaming/mystream.m3u8",
    "isHD": false
  },
  {
    "id": "ar-68",
    "name": "Canal Showsport (720p)",
    "category": "DEPORTES",
    "number": 68,
    "logoUrl": "https://i.imgur.com/0L9tW3Z.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://livestream.lumpentv.com.ar/hls/lumpen.m3u8",
    "isHD": true
  },
  {
    "id": "ar-69",
    "name": "Canal TDC",
    "category": "NOTICIAS",
    "number": 69,
    "logoUrl": "https://i.imgur.com/nPG38B2.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://tdcserver.com:19360/tdconlione-2/tdconlione-2.m3u8",
    "isHD": false
  },
  {
    "id": "ar-70",
    "name": "Canal Universidad",
    "category": "ARGENTINA",
    "number": 70,
    "logoUrl": "https://i.imgur.com/trmPKYw.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videostream.shockmedia.com.ar/hls/canaluniversidadmdp/canaluniversidadmdp.m3u8",
    "isHD": false
  },
  {
    "id": "ar-71",
    "name": "Caras TV (1080p)",
    "category": "ARGENTINA",
    "number": 71,
    "logoUrl": "https://i.imgur.com/7dl4yQY.jpeg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://unlimited1-us.dps.live/carastv/carastv.smil/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-72",
    "name": "Catamarca TV (720p)",
    "category": "NOTICIAS",
    "number": 72,
    "logoUrl": "https://i.imgur.com/CEuPoqG.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.com.ar/canal7catamarca/ngrp:canal7catamarca_all/playlist.m3u8?DVR=",
    "isHD": true
  },
  {
    "id": "ar-73",
    "name": "Celta TV (240p)",
    "category": "ARGENTINA",
    "number": 73,
    "logoUrl": "https://i.imgur.com/rwoIF4w.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vivo.solumedia.com:19360/celta/celta.m3u8",
    "isHD": false
  },
  {
    "id": "ar-74",
    "name": "Chaco TV (720p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 74,
    "logoUrl": "https://i.imgur.com/b6RerDw.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://wowzasrv.chaco.gov.ar/Streamtv/chacotv/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-75",
    "name": "Chacra TV",
    "category": "ARGENTINA",
    "number": 75,
    "logoUrl": "https://i.imgur.com/gy7AEfO.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://5f700d5b2c46f.streamlock.net/chacratv/chacratv/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-76",
    "name": "Chamame TV",
    "category": "MUSICA",
    "number": 76,
    "logoUrl": "https://i.imgur.com/JigzJck.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://srv4.zcast.com.br/chamametv/chamametv/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-77",
    "name": "Cinecanal South (1080p)",
    "category": "CINE",
    "number": 77,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/CinecanalLA.png/960px-CinecanalLA.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://45.162.193.35/CINECANAL/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-78",
    "name": "Ciudad Magica (720p)",
    "category": "ARGENTINA",
    "number": 78,
    "logoUrl": "https://i.imgur.com/HJkSz2U.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://lbgo.bozztv.com/ssh101/ssh101/verycoolfgr/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-79",
    "name": "Comedy Central Latin America (1080p)",
    "category": "ARGENTINA",
    "number": 79,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Comedy_Central_2018.svg/960px-Comedy_Central_2018.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://15.204.246.24:8080/ComedyCentralHD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-80",
    "name": "Correa Radiovision",
    "category": "ARGENTINA",
    "number": 80,
    "logoUrl": "https://i.imgur.com/bNCGzjf.jpeg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.net:4443/correadigital/canal12/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-81",
    "name": "Corrientes TV",
    "category": "ARGENTINA",
    "number": 81,
    "logoUrl": "https://i.imgur.com/7PBkvRp.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://617c5175c970b.streamlock.net:4444/13max2/live13maxtv2026/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-82",
    "name": "Cosmos Tv",
    "category": "NOTICIAS",
    "number": 82,
    "logoUrl": "https://i0.wp.com/fmcosmos.com/wp-content/uploads/2021/11/COSMOS-TV.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://tv.mediacp.eu:19360/cosmos/cosmos.m3u8",
    "isHD": false
  },
  {
    "id": "ar-83",
    "name": "Cosmos Tv",
    "category": "NOTICIAS",
    "number": 83,
    "logoUrl": "https://i0.wp.com/fmcosmos.com/wp-content/uploads/2021/11/COSMOS-TV.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://canaletaplus.com:3922/live/cosmoslive.m3u8",
    "isHD": false
  },
  {
    "id": "ar-84",
    "name": "Cumbia Mix (720p)",
    "category": "MUSICA",
    "number": 84,
    "logoUrl": "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/6901dfd41a05195b77301d7b/b306e57e4_Logo-TV-C.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://cloud.tvomix.com/CUMBIAMIX/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-85",
    "name": "Disney Channel Latin America (1080p)",
    "category": "ARGENTINA",
    "number": 85,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/f/ff/2024_Disney_Channel_text_logo.svg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://15.204.246.24:8080/DisneyHD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-86",
    "name": "Disney Channel Latin America Panregional HD (1080p)",
    "category": "ARGENTINA",
    "number": 86,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/f/ff/2024_Disney_Channel_text_logo.svg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://45.134.141.161:2200/ARG/Disney_Channel/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-87",
    "name": "Disney Jr. Latin America South (1080p)",
    "category": "ARGENTINA",
    "number": 87,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e3/2024_Disney_Jr._Logo.svg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://45.185.163.75:8000/play/a016/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-88",
    "name": "Disney Jr. Latin America South HD (1080p)",
    "category": "ARGENTINA",
    "number": 88,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e3/2024_Disney_Jr._Logo.svg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://45.134.141.161:2200/ARG/Disney_Junior/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-89",
    "name": "E! Latin America (1080p)",
    "category": "NOTICIAS",
    "number": 89,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/E%21_Logo_2012.svg/500px-E%21_Logo_2012.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://bantel-cdn1.iptvperu.tv:1935/btnscrtn/entertainment.stream/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-90",
    "name": "Eco TV",
    "category": "ARGENTINA",
    "number": 90,
    "logoUrl": "https://i.imgur.com/V2ldYVd.jpg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.arcast.com.ar/ecotv/ngrp:ecotv_all/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-91",
    "name": "El Gourmet South (1080p)",
    "category": "ARGENTINA",
    "number": 91,
    "logoUrl": "https://i.imgur.com/ByMyRI9.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://iptv.bitred.cl/ELGOURMET_HD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-92",
    "name": "El Nueve (1080p)",
    "category": "ARGENTINA",
    "number": 92,
    "logoUrl": "https://i.imgur.com/cJHP7bU.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://15.204.246.24:8080/elnueveHD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-93",
    "name": "El Siete (1080p)",
    "category": "ARGENTINA",
    "number": 93,
    "logoUrl": "https://i.imgur.com/yKb7nfP.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://edgectc.com/CANAL7_MZA/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-94",
    "name": "El Trece (1080p)",
    "category": "ARGENTINA",
    "number": 94,
    "logoUrl": "https://i.imgur.com/TrgBAdA.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://15.204.246.24:8080/eltreceHD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-95",
    "name": "Europa Europa (1080p)",
    "category": "ARGENTINA",
    "number": 95,
    "logoUrl": "https://i.imgur.com/w5SOfyJ.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://cdn1tlinkgo.tlink.cl/europaeuropa/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-96",
    "name": "FIFA+ Hispanic America (720p)",
    "category": "DEPORTES",
    "number": 96,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/FIFA%2B_(2025).svg/960px-FIFA%2B_(2025).svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://6c849fb3.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/TEctbXhfRklGQVBsdXNTcGFuaXNoLTFfSExT/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-97",
    "name": "Folcloreando TV",
    "category": "ARGENTINA",
    "number": 97,
    "logoUrl": "https://folcloreando.com/wp-content/uploads/elementor/thumbs/logo-qvcz16ulfxe7qqvftihvlcoku8l2hux59qcndiy3qo.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stmvideo6.livecastv.com/radioactivasanjuan/radioactivasanjuan/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-98",
    "name": "Fox Sports (720p) [Not 24/7]",
    "category": "DEPORTES",
    "number": 98,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/FOX_Sports_logo.svg/960px-FOX_Sports_logo.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://futbol9865.ultratv13.workers.dev/deportivo111/78.m3u8",
    "isHD": true
  },
  {
    "id": "ar-99",
    "name": "FX Latin America South (720p)",
    "category": "ARGENTINA",
    "number": 99,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/FX_International_logo.svg/960px-FX_International_logo.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://72.1.184.5:8089/play/a05i/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-100",
    "name": "IP Noticias (720p)",
    "category": "NOTICIAS",
    "number": 100,
    "logoUrl": "https://i.imgur.com/dbu9nx4.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://twitch-m3u8.bastypro112.workers.dev/argentina_12tw/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-101",
    "name": "Itel TV Canal 2",
    "category": "ARGENTINA",
    "number": 101,
    "logoUrl": "https://i.imgur.com/OxmpRDx.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://proxystream.iteltv.com.ar/output/iteltv/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-102",
    "name": "Kpop Mix (720p)",
    "category": "ARGENTINA",
    "number": 102,
    "logoUrl": "https://tvomix.com/Logos/Kpopmix.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://cloud.tvomix.com/KPOPMIX/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-103",
    "name": "La 100 (1080p)",
    "category": "MUSICA",
    "number": 103,
    "logoUrl": "https://cloudfront-us-east-1.images.arcpublishing.com/radiomitre/CZJMM4BJVRFANO4VGMMYWSTEVE.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://mdstrm.com/live-stream-playlist/68b74fd1d6512526f1f7c75a.m3u8",
    "isHD": true
  },
  {
    "id": "ar-104",
    "name": "La Nacion + (576p)",
    "category": "ARGENTINA",
    "number": 104,
    "logoUrl": "https://i.imgur.com/Gj1kqH5.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://playcom.trapemn.tv:1935/transcoderip/lanacionplus.stream/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-105",
    "name": "LAMIL35 TV",
    "category": "ARGENTINA",
    "number": 105,
    "logoUrl": "https://www.appcreator24.com/srv/imgs/gen/3544498_ico.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vd01.streaminghd.net.ar:3349/live/bzuctkgnlive.m3u8",
    "isHD": false
  },
  {
    "id": "ar-106",
    "name": "Más FM 95.9 (720p)",
    "category": "MUSICA",
    "number": 106,
    "logoUrl": "https://i.imgur.com/TJ4gWQM.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vivo.solumedia.com:19360/masfm/masfm.m3u8",
    "isHD": true
  },
  {
    "id": "ar-107",
    "name": "Mercurio Noticias",
    "category": "NOTICIAS",
    "number": 107,
    "logoUrl": "https://i.imgur.com/sfd87LX.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videostream.shockmedia.com.ar/hls/mercuriotv/mercuriotv.m3u8",
    "isHD": false
  },
  {
    "id": "ar-108",
    "name": "Metro TV (720p)",
    "category": "ARGENTINA",
    "number": 108,
    "logoUrl": "https://i.imgur.com/7f7M7zl.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://streamtv12.ddns.net:5443/LiveApp/streams/193945633734205616732920.m3u8",
    "isHD": true
  },
  {
    "id": "ar-109",
    "name": "Misiones Cuatro",
    "category": "ARGENTINA",
    "number": 109,
    "logoUrl": "https://i.imgur.com/HXRpRlK.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://iptv.ixfo.com.ar:30443/live-HD/MISIONES4/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-110",
    "name": "MTV Latin America (1080p)",
    "category": "ARGENTINA",
    "number": 110,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/MTV_2021_%28brand_version%29.svg/960px-MTV_2021_%28brand_version%29.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://15.204.246.24:8080/MTVHD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-111",
    "name": "MusicTop (1080p)",
    "category": "MUSICA",
    "number": 111,
    "logoUrl": "https://cdn.mitvstatic.com/channels/ar_musictop_m.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream-gtlc.telecentro.net.ar/hls/musictophls/0/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-112",
    "name": "Neo TV",
    "category": "ARGENTINA",
    "number": 112,
    "logoUrl": "https://i.imgur.com/Xtu85tb.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videostream.shockmedia.com.ar:19360/neotvdigital/neotvdigital.m3u8",
    "isHD": false
  },
  {
    "id": "ar-113",
    "name": "NET TV (720p)",
    "category": "ARGENTINA",
    "number": 113,
    "logoUrl": "https://i.imgur.com/IhJ0BjF.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://45.134.141.161:2200/ARG/Net_TV/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-114",
    "name": "NG Federal (720p)",
    "category": "ARGENTINA",
    "number": 114,
    "logoUrl": "https://i.imgur.com/lJCIqYn.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://www.coninfo.net:1935/tvlink/live/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-115",
    "name": "Panc TV (720p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 115,
    "logoUrl": "https://i.imgur.com/u1dnEVv.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://panel.host-live.com:19360/20004/20004.m3u8",
    "isHD": true
  },
  {
    "id": "ar-116",
    "name": "Power Max Radio TV (720p)",
    "category": "ARGENTINA",
    "number": 116,
    "logoUrl": "https://i.ibb.co/qgZLYDj/channels4-profile-6.jpg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videostream.shockmedia.com.ar:19360/radio1045/radio1045.m3u8",
    "isHD": true
  },
  {
    "id": "ar-117",
    "name": "PowerHD",
    "category": "ARGENTINA",
    "number": 117,
    "logoUrl": "https://i.imgur.com/15gMDG0.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://live2.tensila.com/1-1-1.power-tv/hls/master.m3u8",
    "isHD": true
  },
  {
    "id": "ar-118",
    "name": "Quantica TV",
    "category": "NOTICIAS",
    "number": 118,
    "logoUrl": "https://i.imgur.com/6f8EYC2.jpeg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videostream.shockmedia.com.ar:19360/quanticatv/quanticatv.m3u8",
    "isHD": false
  },
  {
    "id": "ar-119",
    "name": "Quiero Musica en mi Idioma (1080p)",
    "category": "MUSICA",
    "number": 119,
    "logoUrl": "https://i.imgur.com/RO9Dz3X.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://177.234.249.178:8888/MTV/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-120",
    "name": "Radio Conexion Web TV (720p)",
    "category": "MUSICA",
    "number": 120,
    "logoUrl": "https://i.imgur.com/pXS38zo.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://tuvideoonline.com.ar:3391/live/radioconexionlive.m3u8",
    "isHD": true
  },
  {
    "id": "ar-121",
    "name": "Radio Maria TV (1080p)",
    "category": "ARGENTINA",
    "number": 121,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/fr/1/1f/Radio_Maria_logo.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://radiomaria.inovanex.stream/stream.m3u8",
    "isHD": true
  },
  {
    "id": "ar-122",
    "name": "Radio Realpolitik (720p)",
    "category": "MUSICA",
    "number": 122,
    "logoUrl": "https://i.imgur.com/L9KCdTX.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vivo.solumedia.com:19360/realpolitik/realpolitik.m3u8",
    "isHD": true
  },
  {
    "id": "ar-123",
    "name": "Radio Sublime Gracia TV (720p)",
    "category": "ARGENTINA",
    "number": 123,
    "logoUrl": "https://i.ibb.co/P9jgTz4/c49b986afb751882bcbee57f9c9b20d7-350x210.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://5f700d5b2c46f.streamlock.net/sublime/sublime/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-124",
    "name": "Radio TV Neuquén (720p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 124,
    "logoUrl": "https://i.imgur.com/HXBLozl.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://media.neuquen.gov.ar/rtn/television/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-125",
    "name": "Radio UP (1080p)",
    "category": "ARGENTINA",
    "number": 125,
    "logoUrl": "https://radioup.com.ar/wp-content/uploads/2025/06/logo-radioup-footer.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://iptv.ixfo.com.ar:30443/live/RadioUpTvStreaming/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-126",
    "name": "Radio Yguazú TV (480p)",
    "category": "ARGENTINA",
    "number": 126,
    "logoUrl": "https://i.imgur.com/kVi0ICm.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://live.enhdtv.com:8081/radioiguazutv/index.m3u8",
    "isHD": false
  },
  {
    "id": "ar-127",
    "name": "Radiocanal San Francisco (1080p)",
    "category": "ARGENTINA",
    "number": 127,
    "logoUrl": "https://i.ibb.co/NNyDWsz/download-8.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://204.199.3.2/.m3u8",
    "isHD": true
  },
  {
    "id": "ar-128",
    "name": "RTN (Neuquén) (720p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 128,
    "logoUrl": "https://i.imgur.com/8xqYg4C.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://media.neuquen.gov.ar/rtn/television/media.m3u8",
    "isHD": true
  },
  {
    "id": "ar-129",
    "name": "San Luis +",
    "category": "ARGENTINA",
    "number": 129,
    "logoUrl": "https://i.imgur.com/bGoGiry.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.radiosmundiales.com/hls/sanluismas/sanluismas.m3u8",
    "isHD": false
  },
  {
    "id": "ar-130",
    "name": "San Pedro TV (1080p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 130,
    "logoUrl": "https://i.imgur.com/UkpXogr.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://iptv.ixfo.com.ar:30443/live/sanpedrotv/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-131",
    "name": "Senal U",
    "category": "ARGENTINA",
    "number": 131,
    "logoUrl": "https://i.ibb.co/yBYcKTj/Senal-U-Uncuyo-en-vivo-Online.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://live20.bozztv.com/giatv/giatv-canal30tda/canal30tda/chunks.m3u8",
    "isHD": false
  },
  {
    "id": "ar-132",
    "name": "Senillosa TV",
    "category": "ARGENTINA",
    "number": 132,
    "logoUrl": "https://yt3.ggpht.com/ytc/AKedOLTrvk7gv0uCQ8QdGREqv6Rtzm4F6UMetdxKub6D=s400-c-k-c0x00ffffff-no-rj",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://player.videohost.click/senillosatv/senillosatv/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-133",
    "name": "Sicardi TV (720p)",
    "category": "ARGENTINA",
    "number": 133,
    "logoUrl": "https://i.imgur.com/W2EUIL2.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vivo.solumedia.com:19360/sicarditv/sicarditv.m3u8",
    "isHD": true
  },
  {
    "id": "ar-134",
    "name": "Solive TV",
    "category": "ARGENTINA",
    "number": 134,
    "logoUrl": "https://i.imgur.com/dyUxugT.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stmv6.voxtvhd.com.br/solivetv/solivetv/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-135",
    "name": "Somos Entre Rios (360p)",
    "category": "ARGENTINA",
    "number": 135,
    "logoUrl": "https://files.catbox.moe/ufv5z0.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://live20.bozztv.com/akamaissh101/ssh101/somosentrerios/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-136",
    "name": "Sony Channel (1080p)",
    "category": "ARGENTINA",
    "number": 136,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Sony_Channel_Logo.png/960px-Sony_Channel_Logo.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://138.121.15.230:9002/SONY/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-137",
    "name": "T5 Satelital",
    "category": "ARGENTINA",
    "number": 137,
    "logoUrl": "https://i.imgur.com/ZcD0rUP.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream.t5satelital.blog/hls/t5satelitalweb.m3u8",
    "isHD": false
  },
  {
    "id": "ar-138",
    "name": "TELE 6 (720p)",
    "category": "ARGENTINA",
    "number": 138,
    "logoUrl": "https://i.imgur.com/p7tt72X.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://lbgo.bozztv.com/ssh101/ssh101/tele6/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-139",
    "name": "Tele Posadas (720p)",
    "category": "ARGENTINA",
    "number": 139,
    "logoUrl": "https://i.imgur.com/88MVgwX.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://live20.bozztv.com/giatv/giatv-teleposadaso01/teleposadaso01/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-140",
    "name": "TeleCinco Trelew (240p)",
    "category": "ARGENTINA",
    "number": 140,
    "logoUrl": "https://i.imgur.com/ZDenyAE.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videohd.live:19360/8016/8016.m3u8",
    "isHD": false
  },
  {
    "id": "ar-141",
    "name": "Telefe (480p)",
    "category": "ARGENTINA",
    "number": 141,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Telefe_%28nuevo_logo%29.png/960px-Telefe_%28nuevo_logo%29.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://201.190.41.246:8822/play/a036/index.m3u8",
    "isHD": false
  },
  {
    "id": "ar-142",
    "name": "Telefe Buenos Aires (1080p)",
    "category": "ARGENTINA",
    "number": 142,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Telefe_%28nuevo_logo%29.png/960px-Telefe_%28nuevo_logo%29.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://45.134.141.161:2200/ARG/TELEFE_HD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-143",
    "name": "Telefe Interior (720p)",
    "category": "ARGENTINA",
    "number": 143,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Telefe_%28nuevo_logo%29.png/960px-Telefe_%28nuevo_logo%29.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://200.91.32.158:8080/telefehdvalle/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-144",
    "name": "Telefe Rosario [Geo-blocked]",
    "category": "ARGENTINA",
    "number": 144,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Telefe_Rosario_%282018%29.png/960px-Telefe_Rosario_%282018%29.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://cdn-cirion01.sensa.com.ar/output/ARR2/TelefeRosarioH/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-145",
    "name": "Telemax",
    "category": "ARGENTINA",
    "number": 145,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Telemax_Argentina_%282018%29.png/960px-Telemax_Argentina_%282018%29.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stream-gtlc.telecentro.net.ar/hls/telemaxhls/main.m3u8",
    "isHD": false
  },
  {
    "id": "ar-146",
    "name": "Telemundo Internacional (1080p)",
    "category": "ARGENTINA",
    "number": 146,
    "logoUrl": "https://i.imgur.com/j2O4ndp.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://138.121.15.230:9002/TELEMUNDO/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-147",
    "name": "Telenord Corrientes (1080p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 147,
    "logoUrl": "https://i.imgur.com/yqXORkt.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://www.coninfo.net:1935/previsoratv/live/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-148",
    "name": "Telesol (1080p)",
    "category": "ARGENTINA",
    "number": 148,
    "logoUrl": "https://i.imgur.com/79sTxtP.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://cdn1.tvlin.net/open/telesol/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-149",
    "name": "The Cabbin FM",
    "category": "MUSICA",
    "number": 149,
    "logoUrl": "https://files.catbox.moe/2vlskg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://5f700d5b2c46f.streamlock.net/thecabinn/thecabinn/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-150",
    "name": "TIV Television (720p)",
    "category": "ARGENTINA",
    "number": 150,
    "logoUrl": "https://i.imgur.com/gsgXGEj.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://videohd.live:19360/8008/8008.m3u8",
    "isHD": true
  },
  {
    "id": "ar-151",
    "name": "TN (1080p)",
    "category": "NOTICIAS",
    "number": 151,
    "logoUrl": "https://i.imgur.com/vFwPhPS.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://15.204.246.24:8080/TNHD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-152",
    "name": "TNT Novelas (1080p)",
    "category": "ARGENTINA",
    "number": 152,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/TNT_Novelas_2025.svg/1920px-TNT_Novelas_2025.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://190.93.224.42/TNT-NOVELAS/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-153",
    "name": "TV Canal 72",
    "category": "ARGENTINA",
    "number": 153,
    "logoUrl": "https://tvcanal72.com.ar/wp-content/uploads/2022/08/LOGO-CANAL-72-1-1024x256.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stmv1.voxtvhd.com.br/canal72tv2/canal72tv2/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-154",
    "name": "TV Maná Argentina (576p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 154,
    "logoUrl": "https://i.imgur.com/jars0mP.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://w2.manasat.com/tvmana-ar/smil:tvmana-ar.smil/playlist.m3u8",
    "isHD": false
  },
  {
    "id": "ar-155",
    "name": "TV Publica Fueguina (1080p)",
    "category": "ARGENTINA",
    "number": 155,
    "logoUrl": "https://i.imgur.com/4dUvFqa.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://nd106.republicaservers.com/hls/c8094/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-156",
    "name": "TV Solidaria (576p)",
    "category": "ARGENTINA",
    "number": 156,
    "logoUrl": "https://i.imgur.com/M0fMypR.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://canadaremar2.todostreaming.es/live/argentina-web.m3u8",
    "isHD": false
  },
  {
    "id": "ar-157",
    "name": "TV Universidad",
    "category": "ARGENTINA",
    "number": 157,
    "logoUrl": "https://i.imgur.com/0MXsQ25.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://stratus.stream.cespi.unlp.edu.ar/hls/tvunlp.m3u8",
    "isHD": false
  },
  {
    "id": "ar-158",
    "name": "TyC Sports (1080p)",
    "category": "DEPORTES",
    "number": 158,
    "logoUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/TyC_Sports_logo.svg/960px-TyC_Sports_logo.svg.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "http://45.181.87.106/TYCSPORTSHD/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-159",
    "name": "Unife TV",
    "category": "ARGENTINA",
    "number": 159,
    "logoUrl": "https://i.imgur.com/TLM592m.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://cdn.mycloudstream.io/hls/live/broadcast/xundwjvp/index.m3u8",
    "isHD": false
  },
  {
    "id": "ar-160",
    "name": "Uniteve (720p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 160,
    "logoUrl": "https://pbs.twimg.com/profile_images/720276300888453120/a_SDOmBc_400x400.jpg",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://vivo.solumedia.com:19360/uniteve/uniteve.m3u8",
    "isHD": true
  },
  {
    "id": "ar-161",
    "name": "Urban Mix (720p)",
    "category": "ARGENTINA",
    "number": 161,
    "logoUrl": "https://tvomix.com/Logos/Urbanmix.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://cloud.tvomix.com/URBANMIX/index.m3u8",
    "isHD": true
  },
  {
    "id": "ar-162",
    "name": "VerTV (VTV) (720p) [Not 24/7]",
    "category": "ARGENTINA",
    "number": 162,
    "logoUrl": "https://i.imgur.com/TLaausJ.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://5f700d5b2c46f.streamlock.net/vertv/vertv/playlist.m3u8",
    "isHD": true
  },
  {
    "id": "ar-163",
    "name": "Villa Mantero TV",
    "category": "ARGENTINA",
    "number": 163,
    "logoUrl": "https://i.imgur.com/mmEenTm.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://micanal.ovh/livestreams/515.AUTOOAAZ721F.m3u8",
    "isHD": false
  },
  {
    "id": "ar-164",
    "name": "Xama TV",
    "category": "ARGENTINA",
    "number": 164,
    "logoUrl": "https://i.imgur.com/dcNzVNN.png",
    "logoEmoji": "📺",
    "nowPlaying": "Transmisión en Vivo HD (iptv-org)",
    "streamUrl": "https://srs.unsj.edu.ar/live/xama/xama.flv",
    "isHD": false
  }
];

export const MOVIES_CATALOG: Movie[] = [
  {
    id: 'mov-coco',
    title: 'Coco (2017)',
    category: 'INFANTIL',
    year: 2017,
    duration: '1h 45m',
    rating: 'IMDb 8.4',
    synopsis: 'El joven Miguel sueña con convertirse en músico y accidentalmente se encuentra atrapado en la deslumbrante y colorida Tierra de los Muertos.',
    posterEmoji: '🎸',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2018/01/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/secret-tempest-196513.appspot.com/Coco.2017.OK.mp4',
  },
  {
    id: 'mov-veronica',
    title: 'Verónica (2017)',
    category: 'TERROR',
    year: 2017,
    duration: '1h 45m',
    rating: 'IMDb 6.2',
    synopsis: 'En Madrid en los años 90, una joven debe proteger a sus hermanos menores tras realizar una sesión de Ouija con sus amigas durante un eclipse solar.',
    posterEmoji: '👻',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2018/03/MV5BMmRkMDQzYzItZDFhMS00YzM1LTk0ZGMtZmExMzdiNzEwOTE4XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/secret-tempest-196513.appspot.com/Veronica.2017.Castellano.mp4',
  },
  {
    id: 'mov-insidious4',
    title: 'La Noche del Demonio: La Última Llave',
    category: 'TERROR',
    year: 2018,
    duration: '1h 43m',
    rating: 'IMDb 5.7',
    synopsis: 'La parapsicóloga Elise Rainier enfrenta su caso más aterrador al ser llamada a investigar los sucesos paranormales en su propia casa de la infancia.',
    posterEmoji: '🔑',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2018/03/MV5BMTUxODU0NjQ2Nl5BMl5BanBnXkFtZTgwMTc4NDQ0MzI@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/secret-tempest-196513.appspot.com/Insidious.The.Last.Key.2018.mp4',
  },
  {
    id: 'mov-guardians2',
    title: 'Guardianes de la Galaxia Vol. 2',
    category: 'ACCION',
    year: 2017,
    duration: '2h 16m',
    rating: 'IMDb 7.6',
    synopsis: 'Los Guardianes deben luchar para mantener unida a su nueva familia mientras descubren los misterios del verdadero linaje de Peter Quill.',
    posterEmoji: '🌌',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2017/08/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/secret-tempest-196513.appspot.com/Guardians.of.the.Galaxy.2.2017.mp4',
  },
  {
    id: 'mov-thor3',
    title: 'Thor 3: Ragnarok',
    category: 'ACCION',
    year: 2017,
    duration: '2h 10m',
    rating: 'IMDb 7.9',
    synopsis: 'Thor está encarcelado al otro lado del universo y debe competir en un combate de gladiadores contra su antiguo aliado, el Increíble Hulk.',
    posterEmoji: '⚡',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2018/01/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/secret-tempest-196513.appspot.com/Thor.Ragnarok.2017.mp4',
  },
  {
    id: 'mov-greatestshowman',
    title: 'El Gran Showman',
    category: 'DRAMA',
    year: 2017,
    duration: '1h 45m',
    rating: 'IMDb 7.5',
    synopsis: 'Celebración del nacimiento del espectáculo y la historia de un visionario que surgió de la nada para crear un espectáculo fascinante.',
    posterEmoji: '🎪',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2018/03/MV5BYjQ0ZWJkYjMtYjJmYS00MjJiLTg3NTYtMmIzN2E2Y2YwZmUyXkEyXkFqcGdeQXVyNjk5NDA3OTk@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/secret-tempest-196513.appspot.com/The.Greatest.Showman.2017.mp4',
  },
  {
    id: 'mov-jumanji2',
    title: 'Jumanji: Bienvenidos a la Jungla',
    category: 'ACCION',
    year: 2017,
    duration: '1h 59m',
    rating: 'IMDb 6.9',
    synopsis: 'Cuatro adolescentes son absorbidos por un videojuego mágico y la única forma de escapar es trabajar juntos para terminar el juego.',
    posterEmoji: '🎮',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2018/03/MV5BMTkyNDQ1MDc5OV5BMl5BanBnXkFtZTgwOTcyNzI2MzI@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/secret-tempest-196513.appspot.com/Jumanji.2017.mp4',
  },
  {
    id: 'mov-starwars8',
    title: 'Star Wars: Los Últimos Jedi',
    category: 'SCIFI',
    year: 2017,
    duration: '2h 32m',
    rating: 'IMDb 7.0',
    synopsis: 'Rey desarrolla sus nuevas habilidades con la guía de Luke Skywalker mientras la Resistencia se prepara para la batalla contra la Primera Orden.',
    posterEmoji: '⚔️',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2018/03/MV5BMjQ1MzcxNjg4N15BMl5BanBnXkFtZTgwNzgwMjY4MzI@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/secret-tempest-196513.appspot.com/Star.Wars.The.Last.Jedi.2017.mp4',
  },
  {
    id: 'mov-justiceleague',
    title: 'Liga de la Justicia',
    category: 'ACCION',
    year: 2017,
    duration: '2h 00m',
    rating: 'IMDb 6.1',
    synopsis: 'Impulsado por su fe restaurada en la humanidad e inspirado por el acto abnegado de Superman, Bruce Wayne recluta a nuevos aliados.',
    posterEmoji: '🛡️',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2018/02/MV5BYWVhZjZkYTItOGIwYS00NmRkLWJlYjctMWM0ZjFmMDU4ZjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/secret-tempest-196513.appspot.com/Justice%20League%20(2017)%20720%20Sub.mp4',
  },
  {
    id: 'mov-shapeofwater',
    title: 'La Forma del Agua',
    category: 'SCIFI',
    year: 2017,
    duration: '2h 03m',
    rating: 'IMDb 7.3',
    synopsis: 'En un centro de investigación de alta seguridad, una mujer muda entabla una relación secreta con un anfibio humanoide prisionero.',
    posterEmoji: '🧜‍♂️',
    posterUrl: 'https://www.cuevana2.tv/wp-content/uploads/2018/01/MV5BNGNiNWQ5M2MtNGI0OC00MDA2LWI5NzEtMmZiYjVjMDEyOWYzXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg',
    streamUrl: 'https://storage.googleapis.com/new-project-189619.appspot.com/shapagua.mp4',
  },
];

export const SERIES_CATALOG: Series[] = [
  {
    id: 'ser-1',
    title: 'El Juego del Calamar - Temporada 2',
    category: 'DRAMA',
    seasonsCount: 2,
    episodesCount: 18,
    rating: 'IMDb 8.5',
    synopsis: 'Cientos de jugadores con problemas de dinero aceptan una extraña invitación a competir en juegos infantiles por un premio millonario.',
    posterEmoji: '🦑',
    episodes: [
      { id: 'ep-101', episodeNumber: 1, title: 'Episodio 1: Red Light, Green Light', duration: '55m', synopsis: 'Los jugadores descubren las mortales reglas del concurso.', streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4' },
    ],
  },
];
